/**
 * Business context: bridges the current named GPX document to swisstopo's
 * documented `/u/` hand-off. The document may be generated by Via Helvetica or
 * retained from an imported read-only GPX. It is uploaded only when the user
 * explicitly requests swisstopo transfer; the configured Worker returns a
 * temporary public URL that swisstopo can fetch from the phone.
 */
import { QR_MAX_TEXT_BYTES } from './qrCode';

/** Official web hand-off prefix documented by swisstopo for external GPX URLs. */
const SWISSTOPO_IMPORT_URL_PREFIX = 'https://swisstopo.app/u/';
/** One upload should fail quickly instead of leaving the export dialog busy indefinitely. */
const SWISSTOPO_SHARE_REQUEST_TIMEOUT_MS = 15_000;
/** Keep in sync with the Worker cap; oversized imported recordings stay locally exportable. */
export const SWISSTOPO_SHARE_MAX_GPX_BYTES = 2 * 1024 * 1024;

/** Temporary route hand-off returned after a successful GPX upload. */
export interface SwisstopoShare {
  /** Public temporary GPX URL consumed by swisstopo. */
  gpxUrl: string;
  /** Official swisstopo hand-off URL encoded into the QR code. */
  swisstopoUrl: string;
  /** ISO expiration time supplied by the Worker, or `null` if omitted. */
  expiresAt: string | null;
}

/** Worker response contract intentionally kept smaller than the GPX payload. */
interface ShareUploadResponse {
  gpxUrl?: unknown;
  expiresAt?: unknown;
}

/** User-actionable failure categories exposed by the temporary share contract. */
export type SwisstopoShareErrorCode =
  | 'tooLarge'
  | 'unsupported'
  | 'temporary';

/** Expected share failure carrying a stable category for localized UI messages. */
export class SwisstopoShareError extends Error {
  /** Stable category used by the export dialog. */
  readonly code: SwisstopoShareErrorCode;

  constructor(code: SwisstopoShareErrorCode, message: string) {
    super(message);
    this.name = 'SwisstopoShareError';
    this.code = code;
  }
}

/** Reads the optional Worker base URL at call time so Vite test env stubs work. */
function getShareServiceBaseUrl(): string {
  return (import.meta.env.VITE_SWISSTOPO_SHARE_SERVICE_URL ?? '')
    .trim()
    .replace(/\/+$/, '');
}

/** Returns whether the optional swisstopo hand-off Worker is configured. */
export function isSwisstopoShareConfigured(): boolean {
  return getShareServiceBaseUrl().length > 0;
}

/**
 * Encodes an ordinary URL with RFC 4648 base64url without padding.
 *
 * @param value - UTF-8 URL text to encode.
 * @returns Base64url text suitable for the swisstopo `/u/` path segment.
 */
export function encodeBase64Url(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = '';

  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }

  return window
    .btoa(binary)
    .replaceAll('+', '-')
    .replaceAll('/', '_')
    .replace(/=+$/u, '');
}

/**
 * Builds the official swisstopo `/u/` URL for one temporary public GPX URL.
 *
 * @param gpxUrl - Public HTTPS URL from which swisstopo can fetch the GPX.
 * @returns Official swisstopo hand-off URL suitable for a link or QR code.
 * @throws {Error} If the GPX URL is not HTTPS or the resulting hand-off URL
 * exceeds the fixed QR encoder capacity.
 */
export function createSwisstopoImportUrl(gpxUrl: string): string {
  const parsedUrl = new URL(gpxUrl);

  if (parsedUrl.protocol !== 'https:') {
    throw new Error('The temporary GPX URL must use HTTPS.');
  }

  const swisstopoUrl = `${SWISSTOPO_IMPORT_URL_PREFIX}${encodeBase64Url(parsedUrl.toString())}`;
  const payloadLength = new TextEncoder().encode(swisstopoUrl).length;

  if (payloadLength > QR_MAX_TEXT_BYTES) {
    throw new Error(
      'The configured GPX share URL is too long for the built-in QR encoder.',
    );
  }

  return swisstopoUrl;
}

/**
 * Uploads the current named GPX document and prepares its swisstopo hand-off URL.
 *
 * @param gpxDocument - Complete GPX XML generated locally or retained from import.
 * @returns Temporary GPX URL, swisstopo import URL, and optional expiration time.
 * @throws {SwisstopoShareError} If the document is too large, the Worker rejects
 * its format, the service is unavailable, or the returned URL is unusable.
 */
export async function createSwisstopoShare(
  gpxDocument: string,
): Promise<SwisstopoShare> {
  const serviceBaseUrl = getShareServiceBaseUrl();

  if (!serviceBaseUrl) {
    throw new SwisstopoShareError(
      'temporary',
      'The swisstopo GPX share service is not configured.',
    );
  }

  const gpxBytes = new TextEncoder().encode(gpxDocument).byteLength;

  if (gpxBytes > SWISSTOPO_SHARE_MAX_GPX_BYTES) {
    throw new SwisstopoShareError(
      'tooLarge',
      'The GPX document exceeds the swisstopo share size limit.',
    );
  }

  const abortController = new AbortController();
  const timeoutId = window.setTimeout(
    () => abortController.abort(),
    SWISSTOPO_SHARE_REQUEST_TIMEOUT_MS,
  );

  try {
    const response = await fetch(`${serviceBaseUrl}/gpx`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/gpx+xml;charset=utf-8',
      },
      body: gpxDocument,
      cache: 'no-store',
      credentials: 'omit',
      signal: abortController.signal,
    });

    if (!response.ok) {
      const code: SwisstopoShareErrorCode =
        response.status === 413
          ? 'tooLarge'
          : response.status === 400
            ? 'unsupported'
            : 'temporary';

      throw new SwisstopoShareError(
        code,
        `GPX share upload failed with HTTP ${response.status}.`,
      );
    }

    const payload = (await response.json()) as ShareUploadResponse;

    if (typeof payload.gpxUrl !== 'string' || payload.gpxUrl.length === 0) {
      throw new SwisstopoShareError(
        'temporary',
        'The GPX share service returned no public URL.',
      );
    }

    try {
      return {
        gpxUrl: payload.gpxUrl,
        swisstopoUrl: createSwisstopoImportUrl(payload.gpxUrl),
        expiresAt:
          typeof payload.expiresAt === 'string' ? payload.expiresAt : null,
      };
    } catch (error) {
      throw new SwisstopoShareError(
        'temporary',
        error instanceof Error
          ? error.message
          : 'The swisstopo hand-off URL could not be prepared.',
      );
    }
  } finally {
    window.clearTimeout(timeoutId);
  }
}
