/**
 * Business context: defines the structured-clone contract between the map UI
 * and the dedicated dynamic-routing worker. Only plain data crosses this
 * boundary; swissTLM3D cells, graphs, and spatial indexes remain worker-owned.
 */
import type { Coordinate } from 'ol/coordinate.js';

/** Signals that a route corridor exceeded the bounded browser safety limit. */
export class RoutingAreaTooLargeError extends Error {
  constructor(
    message = 'The requested dynamic routing area contains too many swissTLM3D cells.',
  ) {
    super(message);
    this.name = 'RoutingAreaTooLargeError';
  }
}

/** Request that snaps one first waypoint. */
export interface SnapWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the main-thread facade. */
  requestId: number;
  /** Worker operation selected for this message. */
  operation: 'snap';
  /** User-selected EPSG:2056 coordinate to project onto the local network. */
  coordinate: Coordinate;
}

/** Request that routes one section. */
export interface RouteWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the main-thread facade. */
  requestId: number;
  /** Worker operation selected for this message. */
  operation: 'route';
  /** Existing editable-route endpoint in EPSG:2056. */
  startCoordinate: Coordinate;
  /** Newly selected destination in EPSG:2056. */
  endCoordinate: Coordinate;
}

/** Cancels one outstanding operation. */
export interface CancelRoutingWorkerRequest {
  /** Discriminator handled without creating another worker operation. */
  type: 'cancel';
  /** Identifier of the request whose AbortController must be triggered. */
  requestId: number;
}

/** Every message accepted by the worker. */
export type RoutingWorkerRequest =
  | SnapWorkerRequest
  | RouteWorkerRequest
  | CancelRoutingWorkerRequest;

/** Serialized error safe to pass through structured clone. */
export interface SerializedRoutingWorkerError {
  /** Error class name used to reconstruct typed failures on the main thread. */
  name: string;
  /** Human-readable failure message shown or handled by the caller. */
  message: string;
  /** Optional worker-side stack retained for development diagnostics. */
  stack?: string;
}

/** Successful worker response. */
export interface RoutingWorkerSuccessResponse {
  /** Response discriminator used by the main-thread facade. */
  type: 'success';
  /** Identifier of the request promise to resolve. */
  requestId: number;
  /** Structured-clone-safe result whose concrete type depends on the operation. */
  result: unknown;
}

/** Failed worker response. */
export interface RoutingWorkerErrorResponse {
  /** Response discriminator used by the main-thread facade. */
  type: 'error';
  /** Identifier of the request promise to reject. */
  requestId: number;
  /** Plain-data error reconstructed by the main-thread client. */
  error: SerializedRoutingWorkerError;
}

/** Non-blocking routing notices emitted independently from one request result. */
export type RoutingWorkerNotice =
  /** Optional hiking geometry was rejected; GeoAdmin continues roads-only. */
  | 'hiking-enrichment-unavailable'
  /** Binary delivery or integrity failed; the complete session uses GeoAdmin. */
  | 'precomputed-routing-unavailable';

/** Session notice posted when the worker changes its provider strategy. */
export interface RoutingWorkerNoticeResponse {
  /** Response discriminator handled without resolving a request promise. */
  type: 'notice';
  /** Stable notice code translated by the main-thread route controller. */
  notice: RoutingWorkerNotice;
}

/** Every response emitted by the worker. */
export type RoutingWorkerResponse =
  | RoutingWorkerSuccessResponse
  | RoutingWorkerErrorResponse
  | RoutingWorkerNoticeResponse;
